# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/
version: 2.1
jobs:
  build_test:
    macos:
      xcode: "14.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          command: xcodebuild GithubUsers.xcodeproj -scheme "CurrencyExchanger" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=16.0" -enableCodeCoverage YES test
      - store_test_results:
          path: test-results

workflows:
  version: 2.1
  primary:
    jobs:
      - build_test
